version: '3.8'
services:
  hardhat-node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile.hardhat
    ports:
      - "8545:8545"  # the node
    # volumes:
      # - .:/usr/src/app
      # - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
