services:
  dapps-deployer:
    container_name: dapps-deployer
    hostname: dapps-deployer
    env_file:
      - .env.tilt.fixed
      - .env.tilt.populated
    image: dapps-deployer-image
    build:
      dockerfile: tilt/Dockerfile
      context: ../.
    network_mode: "host"
    volumes:
      - tilt-shared-volume:/usr/src/app/shared

volumes:
  tilt-shared-volume:
    name: tilt-shared-volume
