services:
  dapps-deployer:
    container_name: dapps-deployer
    env_file:
      - .env.tilt.fixed
      - .env.tilt.populated
    image: dapps-deployer-image
    build:
      dockerfile: tilt/Dockerfile
      context: ../.
      args:
        - SEQUENCER_PRIVATE_KEY_EVM=${SEQUENCER_PRIVATE_KEY_EVM}
    network_mode: "host"
