services:
  dapps-deployer:
    container_name: dapps-deployer
    hostname: dapps-deployer
    image: dapps-deployer-image
    build:
      dockerfile: tilt/Dockerfile
      context: ../.
    network_mode: "host"
    volumes:
      - tilt-shared-volume:/usr/src/app/shared
    env_file:
      - ../../../.env.tilt.global
    environment:
      - DEPLOY_ENV=localhost

volumes:
  tilt-shared-volume:
    name: tilt-shared-volume
